import assert from 'node:assert/strict';import jsQR from 'jsqr';import {PNG} from 'pngjs';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');const key=process.env.HOST_KEY;assert(key);const base='http://localhost:3780';
const action=async(action,data={})=>{const r=await fetch(base+'/api/action',{method:'POST',body:JSON.stringify({action,admin:key,...data})});assert(r.ok,await r.clone().text());return r.json();};
await action('reset');const config=await(await fetch(base+'/api/config')).json();const png=PNG.sync.read(Buffer.from(config.qr.split(',')[1],'base64'));const qr=jsQR(new Uint8ClampedArray(png.data),png.width,png.height);assert.equal(qr.data,config.join);assert(!qr.data.includes('localhost'));console.log('QR decoded:',qr.data);
const browser=await chromium.launch({headless:true,args:['--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream']});const errors=[];const display=await browser.newPage({viewport:{width:1920,height:1080}});display.on('pageerror',e=>errors.push(e.message));await display.goto(base+'/display');await display.waitForSelector('#join-qr');await display.screenshot({path:'artifacts/festival-1920.png'});
const phone=await browser.newPage({viewport:{width:390,height:844}});phone.on('pageerror',e=>errors.push(e.message));await phone.goto(qr.data);await phone.locator('#name').fill('掃碼社友');await phone.waitForFunction(()=>document.querySelector('#camera-video')?.videoWidth>0);await phone.locator('#capture').click();await phone.locator('#motion-mode').click();await phone.locator('#join').click();await phone.locator('#ready').click();const token=await phone.evaluate(()=>sessionStorage.getItem('moon-token'));
for(let i=1;i<5;i++){const p=await action('join',{name:'社友'+i});await action('ready',{token:p.token});}
await display.waitForTimeout(250);assert.equal(await display.locator('.crew-seat.occupied').count(),5);await display.screenshot({path:'artifacts/festival-full.png'});await action('start');await phone.waitForFunction(()=>JSON.parse(render_game_to_text()).me?.status==='run');
for(let i=0;i<40;i++){const s=await(await fetch(base+'/api/state?token='+token)).json();if(s.me.status==='question')break;await action('move',{token});await new Promise(r=>setTimeout(r,400));}
await phone.waitForSelector('[data-choice]');const choice=await phone.locator('[data-choice]').allTextContents();await phone.locator(`[data-choice="${choice.findIndex(t=>t.includes('業績'))}"]`).click();await display.waitForSelector('.runner.stunned');
await display.screenshot({path:'artifacts/stunned-display.png'});await phone.screenshot({path:'artifacts/stunned-phone.png'});
let state=await(await fetch(base+'/api/state?token='+token)).json();assert.equal(state.me.status,'stunned');const position=state.me.steps;await action('move',{token});state=await(await fetch(base+'/api/state?token='+token)).json();assert.equal(state.me.steps,position);await phone.waitForFunction(()=>JSON.parse(render_game_to_text()).me?.status==='run',null,{timeout:3500});state=await(await fetch(base+'/api/state?token='+token)).json();assert.equal(state.me.stage,1);assert.equal(state.me.steps,0);assert.equal(state.me.correct,0);assert.equal(await display.locator('.runner.stunned').count(),0);
assert.deepEqual(errors,[]);await action('reset');await browser.close();console.log('PASS: QR joins via LAN, five-player lobby updates, wrong answer stuns on both screens, input ignored, resumes after penalty');
