import test from 'node:test';import assert from 'node:assert/strict';import {Game,questions} from '../game.mjs';
const setup=()=>{const g=new Game();for(let i=0;i<5;i++)g.join('玩家'+i).ready=true;g.start();g.advance(3000);return g;};
function reach(g,p){while(p.status==='run'){g.advance(334);g.move(p.token);}}
test('五個名額、準備門檻與開始倒數',()=>{let g=new Game();let p=g.join('社友');assert.throws(()=>g.start());for(let i=0;i<4;i++)g.join('社友');assert.throws(()=>g.join('第六人'));g.players.forEach(p=>p.ready=true);g.start();assert.equal(g.phase,'countdown');g.advance(2999);assert.equal(g.phase,'countdown');g.advance(1);assert.equal(g.phase,'race');assert.throws(()=>g.join('遲到'));});
test('所有題目採二選一，使用者確認的用字與答案',()=>{assert.equal(questions.length,5);assert(questions.every(q=>q.options.length===2));assert.equal(questions[0].options[0],'創造持衡的影響力');assert.equal(questions[3].options[questions[3].correct],'18 歲');});
test('速限、正確回饋、五題完成、中央排名',()=>{const g=setup(),p=g.players[0];g.move(p.token);for(let i=0;i<20;i++)g.move(p.token);assert.equal(p.steps,4);for(let q=0;q<5;q++){reach(g,p);assert.equal(p.status,'question');assert(!JSON.stringify(g.state()).includes('correct":0,"options'));const choice=p.order[p.stage].indexOf(questions[p.stage].correct);g.answer(p.token,choice);assert.equal(p.status,'feedback');g.answer(p.token,1-choice);g.advance(2000);assert.equal(p.correct,q+1);if(q<4)assert.equal(p.steps,20);}assert.equal(p.status,'finished');assert.equal(p.stage,5);assert.equal(g.rankings()[0].id,p.id);});
test('逾時、答錯、暫停、限時與重置',()=>{const g=setup(),p=g.players[0];reach(g,p);g.paused=true;const elapsed=g.elapsed;g.advance(90000);assert.equal(g.elapsed,elapsed);g.paused=false;g.advance(12000);assert.equal(p.status,'stunned');assert.equal(p.correct,0);g.advance(1999);assert.equal(p.stage,0);g.advance(1);assert.equal(p.stage,1);assert.equal(p.steps,0);p.connected=false;g.move(p.token);assert.equal(p.steps,0);g.advance(150000);assert.equal(g.phase,'results');const round=g.round;g.reset();assert.equal(g.phase,'lobby');assert.equal(g.players.length,0);assert.notEqual(round,g.round);});
test('私有題目與 token 不在公開狀態',()=>{const g=setup(),p=g.players[0];reach(g,p);const publicState=JSON.stringify(g.state());assert(!publicState.includes(p.token));assert.equal(g.state().me,null);assert.equal(g.state(p.token).me.question.options.length,2);assert(!('correct' in g.state(p.token).me.question));});

test('答錯立即原地暈眩兩秒，暫停會凍結懲罰，最後一題亦適用',()=>{const g=setup(),p=g.players[0];for(let stage=0;stage<5;stage++){reach(g,p);const position=p.stage*100+p.steps;g.answer(p.token,1-p.order[p.stage].indexOf(questions[p.stage].correct));assert.equal(p.status,'stunned');assert.equal(g.state().players[0].stunRemaining,2000);g.move(p.token);assert.equal(p.stage*100+p.steps,position);g.paused=true;g.advance(5000);assert.equal(g.state(p.token).me.remaining,2000);g.paused=false;g.advance(1999);assert.equal(p.status,'stunned');g.move(p.token);assert.equal(p.stage*100+p.steps,position);g.advance(1);assert.equal(p.stage,stage+1);assert.equal(p.correct,0);if(stage<4){assert.equal(p.status,'run');assert.equal(p.steps,0);}else assert.equal(p.status,'finished');}});
test('真人單人測試可略過準備並完成全部五題；正式仍需五人',()=>{const g=new Game();assert.throws(()=>g.start({testMode:true}));const p=g.join('單人測試');assert.throws(()=>g.start());g.start({testMode:true});assert.equal(p.ready,true);assert.equal(g.testMode,true);assert.throws(()=>g.start({testMode:true}));g.advance(3000);for(let i=0;i<5;i++){reach(g,p);g.answer(p.token,p.order[p.stage].indexOf(questions[p.stage].correct));g.advance(2000);}assert.equal(g.phase,'results');assert.equal(g.rankings()[0].rank,1);g.reset();assert.equal(g.testMode,false);});

test('玩家只能使用搖晃模式，舊點按設定不會啟用',()=>{const g=new Game();assert.equal(g.join('玩家','','tap').mode,'motion');assert.equal(g.join('新玩家').mode,'motion');});
test('同步狀態只含照片網址，不重傳自拍資料',()=>{const g=new Game();const p=g.join('自拍','data:image/jpeg;base64,'+'A'.repeat(60000));const s=JSON.stringify(g.state(p.token));assert(s.length<2000);assert(!s.includes('base64'));assert.equal(g.state().players[0].photo,'/api/photo/'+p.id+'?round='+g.round);});
