import assert from 'node:assert/strict';import jsQR from 'jsqr';import {PNG} from 'pngjs';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');const base=process.env.TEST_BASE_URL,key=process.env.HOST_KEY;assert(base?.startsWith('https://'));assert(key);
const action=async(action,data={})=>{const r=await fetch(base+'/api/action',{method:'POST',body:JSON.stringify({action,admin:key,...data})});assert(r.ok,await r.clone().text());return r.json();};
await action('reset');const browser=await chromium.launch({headless:true});const display=await browser.newPage({viewport:{width:1280,height:720}}),phone=await browser.newPage({viewport:{width:390,height:844}});const errors=[];for(const p of [display,phone])p.on('pageerror',e=>errors.push(e.message));
await display.goto(base+'/display');await display.waitForSelector('#join-qr',{timeout:30000});const qrImg=await display.locator('#join-qr').getAttribute('src');const png=PNG.sync.read(Buffer.from(qrImg.split(',')[1],'base64'));const qr=jsQR(new Uint8ClampedArray(png.data),png.width,png.height);assert.equal(qr.data,base+'/play');await display.screenshot({path:'artifacts/https-display.png'});
await phone.goto(qr.data);await phone.waitForSelector('#motion-mode');assert.equal(await phone.evaluate(()=>isSecureContext),true);await phone.locator('#name').fill('HTTPS 搖晃測試');await phone.locator('#motion-mode').click();assert.match(await phone.locator('#mode-hint').textContent(),/已開啟感應/);await phone.locator('#join').click();await phone.locator('#ready').click();await phone.waitForFunction(()=>JSON.parse(window.render_game_to_text()).me?.ready===true);const token=await phone.evaluate(()=>sessionStorage.getItem('moon-token'));
for(let i=1;i<5;i++){const p=await action('join',{name:'測試'+i});await action('ready',{token:p.token});}await action('start');await phone.waitForFunction(()=>JSON.parse(window.render_game_to_text()).me?.status==='run',{timeout:20000});
await phone.evaluate(()=>{window.dispatchEvent(new DeviceMotionEvent('devicemotion',{accelerationIncludingGravity:{x:-6,y:0,z:0}}));window.dispatchEvent(new DeviceMotionEvent('devicemotion',{accelerationIncludingGravity:{x:6,y:0,z:0}}));});await phone.waitForFunction(()=>JSON.parse(window.render_game_to_text()).me?.steps>=4);await phone.screenshot({path:'artifacts/https-motion.png'});for(let i=0;i<45;i++){const s=await phone.evaluate(()=>JSON.parse(window.render_game_to_text()));if(s.me.status==='question')break;await phone.evaluate(()=>{for(const x of [-6,6])window.dispatchEvent(new DeviceMotionEvent('devicemotion',{accelerationIncludingGravity:{x,y:0,z:0}}));});await phone.waitForTimeout(450);}
await phone.getByRole('button',{name:/創造持久的業績/}).click();await phone.waitForFunction(()=>JSON.parse(window.render_game_to_text()).me?.status==='stunned');await display.waitForSelector('.runner.stunned');await phone.screenshot({path:'artifacts/https-stunned.png'});await phone.waitForFunction(()=>{const s=JSON.parse(window.render_game_to_text());return s.me?.stage===1&&s.me?.status==='run';});const after=await phone.evaluate(()=>JSON.parse(window.render_game_to_text()));assert.equal(after.me.steps,0);assert.equal(after.me.correct,0);
assert.deepEqual(errors,[]);await action('reset');await browser.close();console.log('PASS: public HTTPS, secure context, QR destination, join/start synchronization, simulated motion advances player, wrong answer stun and recovery; real phone sensor test remains.');
