import fs from 'node:fs/promises';
import QRCode from 'qrcode';
const out='pages-site';
await fs.mkdir(out+'/assets',{recursive:true});
for(const file of ['festival.png','rotary-chingshie.png'])await fs.copyFile('public/assets/'+file,out+'/assets/'+file);
await fs.writeFile(out+'/style.css',(await fs.readFile('public/style.css','utf8')).replaceAll('/assets/','./assets/'));
const config=JSON.parse(await fs.readFile('site-config.json','utf8'));
const base=new URL(config.gameBaseUrl);if(base.protocol!=='https:')throw Error('Game URL must use HTTPS');
const join=new URL('play.html',config.homepage).href;
await QRCode.toFile(out+'/assets/join-qr.png',join,{width:440,margin:4,errorCorrectionLevel:'M',color:{dark:'#14233D',light:'#FFFFFF'}});
const head=`<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="清溪扶輪中秋同樂會：自拍變嫦娥，搖晃手機向月亮跑，五道知識題決勝負。"><title>嫦娥奔月大賽 · 清溪扶輪</title><link rel="stylesheet" href="./style.css"></head>`;
await fs.writeFile(out+'/index.html',`${head}<body><main class="festival"><div class="festival-art" aria-hidden="true"></div><div class="festival-shade"></div><header class="festival-top"><div class="brand-lockup"><img src="./assets/rotary-chingshie.png" alt="台北清溪扶輪社 Rotary Club of Taipei Chingshie — Create Lasting Impact"></div><span class="festival-event">清溪扶輪社 <i>✦</i> 中秋同樂會</span><span class="live-dot">邀你一起登月</span></header><section class="festival-main"><div class="festival-copy"><p class="festival-kicker">今晚，換你當嫦娥</p><h1>嫦娥<br><span>奔月大賽</span><sup>✦</sup></h1><p class="festival-tagline">你的大頭，今晚登月！</p><p class="festival-description">揪社友、拍自拍，一起向月亮出發。<br>五人同場，看看誰最懂清溪！</p><div class="how-to"><span><b>01</b> 掃碼自拍</span><span><b>02</b> 搖晃前進</span><span><b>03</b> 答題登月</span></div><p class="rule-note">答對獲得助力　✦　答錯原地暈眩 2 秒</p><div class="links"><a class="link" href="./play.html">手機加入遊戲 →</a><a class="link" href="./display.html">開啟現場大屏 ↗</a></div></div><aside class="boarding-pass"><p class="boarding-eyebrow">MOON EXPRESS</p><h2>掃一下，準備登月</h2><div class="qr-frame"><img src="./assets/join-qr.png" alt="掃碼開啟手機入場頁" width="280" height="280"></div><p class="scan-caption">手機相機掃描 QR 碼</p><p class="wifi-note">開啟動作感應，輕輕左右搖晃</p><div class="ticket-bottom"><span>五位嫦娥同場競速</span><strong>5<small> 道題</small></strong></div></aside></section><footer class="festival-footer"><span>活動開放時可加入。首次開啟若需等待，請稍候讓服務啟動。</span><span>清溪扶輪 · 中秋同樂會</span></footer></main></body></html>`);
for(const role of ['play','display']){const url=new URL('/'+role,base).href;await fs.writeFile(out+'/'+role+'.html',`${head}<body><main class="shell intro"><div class="brand-lockup"><img src="./assets/rotary-chingshie.png" alt="清溪扶輪社"></div><p class="eyebrow" style="margin-top:32px">嫦娥奔月大賽</p><h1>${role==='play'?'準備搖晃登月':'開啟現場大屏'}</h1><p>即將前往現場遊戲。若未自動開啟，請按下方按鈕。</p><a class="link" href="${url}">繼續進入遊戲 →</a><p class="hint">首次開啟可能需要稍候；若仍無法連線，請聯絡主持人。</p><a href="./index.html" class="link">返回首頁</a></main><script>location.replace(${JSON.stringify(url)});</script></body></html>`);}
await fs.writeFile(out+'/.nojekyll','');
console.log('Built public homepage at '+config.homepage);
